### ISSUE TITLE
Every lightning strike generates new Entity

### ISSUE THREAD

**Issue by DarS007** [mrk-its/homeassistant-blitzortung#13]
I installed blitzortung several weeks ago, but only today I had a chance to see it in action :-) There were plenty of thunderstorms in the area. It was fun to watch the lightning counter going up quite fast. But ...
Further checks of HA state revealed plenty (hundred ?) new entities created by the module. I guess this is a wrong behavior and should be corrected.
I did a [screenshoot](https://github.com/DarS007/Miscellaneous.01/raw/master/20200826-HA-Lightning_Strike-error.png) to better illustrate this bug.
My installation:
 - Home Assistant 0.114.1
 - Blitzortung.org lightning detector installed via HACS, configured for detection radius 100km

**Comment by mrk-its** [comment]
This is expected behavior (that's why you see lightnings on the map). You can control number of lightning strike entities by two configuration parameters: "time_window" and "max_tracked_lightnings". By default "time_window" is set to 120 minutes - older entities will be removed. You can also decrease "max_tracked_lightnings" parameter (default value is 100).

**Comment by DarS007** [comment]
Dziex! The concept was only briefly described on the project page, so I clearly misunderstood the way the code works. Thanks for the explanation and your entire contribution!
